questions =  [
    //individualist questions
    {"id": 0, "question": "Others often have a difficult time understanding me.", "effects": {"auth": 2}},
    {"id": 1, "question": "I hate being told what to do.", "effects": {"auth": 2}},
    {"id": 2, "question": "It's hard for me to trust other people.", "effects": {"auth": 2}},
    {"id": 3, "question": "I'm often in my own head.", "effects": {"auth": 2}},
    {"id": 4, "question": "I keep to myself.", "effects": {"auth": 2}},
    {"id": 5, "question": "It's often hard for me to relate to the feelings of others.", "effects": {"auth": 2}},
    //collectivist questions
    {"id": 6, "question": "I fit into the culture around me.", "effects": {"auth": -2}},
    {"id": 7, "question": "When there's a party I like to be with everybody else.", "effects": {"auth": -2}},
    {"id": 8, "question": "I have a lot of friends.", "effects": {"auth": -2}},
    {"id": 9, "question": "I tend to follow rules.", "effects": {"auth": -2}},
    {"id": 10, "question": "I am a very empathetic person.", "effects": {"auth": -2}},
    {"id": 11, "question": "People find that I understand their struggles.", "effects": {"auth": -2}},
    //stoic questions
    {"id": 12, "question": "I like peace and quiet.", "effects": {"right": 2}},
    {"id": 13, "question": "I'd prefer a relaxing chat to a roudy conversation or debate.", "effects": {"right": 2}},
    {"id": 14, "question": "An afternoon in the park sounds better than a night in the club.", "effects": {"right": 2}},
    {"id": 15, "question": "I'm slow to anger.", "effects": {"right": 2}},
    {"id": 16, "question": "I am usually a quiet person.", "effects": {"right": 2}},
    {"id": 17, "question": "I am in control of my emotions.", "effects": {"right": 2}},
    //passionate questions
    {"id": 18, "question": "I am prone to outbursts of emotion.", "effects": {"right": -2}},
    {"id": 19, "question": "I am very expressive.", "effects": {"right": -2}},
    {"id": 20, "question": "People know what I'm feeling.", "effects": {"right": -2}},
    {"id": 21, "question": "I like to dance.", "effects": {"right": -2}},
    {"id": 22, "question": "I am often overwhelmed by my emotions.", "effects": {"right": -2}},
    {"id": 23, "question": "I often express my love for others.", "effects": {"right": -2}},
    //blue questions
    {"id": 24, "question": "Truth is the most important thing to me.", "effects": {"auth": 1, "right": 1, "prog": 1, "blue": 1}},
    {"id": 25, "question": "I like to read.", "effects": {"auth": 1, "right": 1, "blue": 1}},
    {"id": 26, "question": "I enjoy mathematics.", "effects": {"auth": 1, "right": 1, "blue": 1}},
    {"id": 27, "question": "I am willing to investigate thoughts which scare myself or others.", "effects": {"auth": 1, "right": 1, "prog": -1, "blue": 1}},
    {"id": 28, "question": "Philosophy is interesting to me.", "effects": {"auth": 1, "right": 1, "blue": 1}},
    {"id": 29, "question": "I love the natural sciences (like chemistry, biology, and physics).", "effects": {"auth": 1, "right": 1, "blue": 1}},
    {"id": 30, "question": "I am bored by physical activity.", "effects": {"auth": 1, "right": 1, "blue": 1}},
    {"id": 31, "question": "I am a deep thinker.", "effects": {"auth": 1, "right": 1, "blue": 1}},
    //purple questions
    {"id": 32, "question": "It's important to me that I have a big impact on the world around me.", "effects": {"auth": 1, "right": -1, "purple": 1}},
    {"id": 33, "question": "I feel most relaxed when I am the one in charge.", "effects": {"auth": 1, "right": -1, "purple": 1}},
    {"id": 34, "question": "I am a natural leader.", "effects": {"auth": 1, "right": -1, "purple": 1}},
    {"id": 35, "question": "If someone like me were in charge, the world would be a better place.", "effects": {"auth": 1, "right": -1, "purple": 1}},
    {"id": 36, "question": "I consider myself a visionary.", "effects": {"auth": 1, "right": -1, "purple": 1}},
    {"id": 37, "question": "My job is to bring order to disorder.", "effects": {"auth": 1, "right": -1, "prog": 1, "purple": 1}},
    {"id": 38, "question": "There should be no authority over me.", "effects": {"auth": 1, "right": -1, "prog": -1, "purple": 1}},
    {"id": 39, "question": "I am strong-willed.", "effects": {"auth": 1, "right": -1, "purple": 1}},
    //red questions
    {"id": 40, "question": "I like working to bring about the vision of a leader whom I respect.", "effects": {"auth": -1, "right": -1, "prog": 1, "red": 1}},
    {"id": 41, "question": "I identify with my body just as much as my mind.", "effects": {"auth": -1, "right": -1, "red": 1}},
    {"id": 42, "question": "I am very physically active.", "effects": {"auth": -1, "right": -1, "red": 1}},
    {"id": 43, "question": "I care more about day-to-day practical concerns than ideological ones.", "effects": {"auth": -1, "right": -1, "red": 1}},
    {"id": 44, "question": "I am a good team player.", "effects": {"auth": -1, "right": -1, "red": 1}},
    {"id": 45, "question": "I would do something I felt was right even if it violates ethics.", "effects": {"auth": -1, "right": -1, "prog": -1, "red": 1}},
    {"id": 46, "question": "It is easy for me to find comradery.", "effects": {"auth": -1, "right": -1, "red": 1}},
    {"id": 47, "question": "I am skilled at physical activities, like sports or darts.", "effects": {"auth": -1, "right": -1, "red": 1}},
    //yellow questions
    {"id": 48, "question": "I am a spiritual person.", "effects": {"auth": -1, "right": 1, "yellow": 1}},
    {"id": 49, "question": "People describe me as a good listener.", "effects": {"auth": -1, "right": 1, "yellow": 1}},
    {"id": 50, "question": "I love to garden or take care of animals.", "effects": {"auth": -1, "right": 1, "yellow": 1}},
    {"id": 51, "question": "I am very perceptive.", "effects": {"auth": -1, "right": 1, "yellow": 1}},
    {"id": 52, "question": "Everything is ultimately just leaves blowing in the wind, nothing is eternal.", "effects": {"auth": -1, "right": 1, "prog": -1, "yellow": 1}},
    {"id": 53, "question": "We should all seek to be part of something greater than ourselves.", "effects": {"auth": -1, "right": 1, "prog": 1, "yellow": 1}},
    {"id": 54, "question": "When I'm with friends, I prefer relaxing activities to high energy ones.", "effects": {"auth": -1, "right": 1, "yellow": 1}},
    {"id": 55, "question": "I am not easily fooled.", "effects": {"auth": -1, "right": 1, "yellow": 1}},
    //light questions
    {"id": 56, "question": "I believe in the monotheistic God.", "effects": {"prog": 1}},
    {"id": 57, "question": "I am very organized.", "effects": {"prog": 1}},
    {"id": 58, "question": "There is an objective morality.", "effects": {"prog": 1}},
    {"id": 59, "question": "Rules and regulations are very important.", "effects": {"prog": 1}},
    //dark questions
    {"id": 60, "question": "There are many truths for different people.", "effects": {"prog": -1}},
    {"id": 61, "question": "It's usually good to shake-up the status quo.", "effects": {"prog": -1}},
    {"id": 62, "question": "Organized religion is a corruption of spirituality.", "effects": {"prog": -1}},
    {"id": 63, "question": "Better to rule in hell than serve in heaven.", "effects": {"prog": -1}},
];
